version: '3.8'
services:
  edc-ui:
    # image: ghcr.io/truzzt/edc-ui:1.0.0-alpha.2
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    ports:
      - '11000:80'
    environment:
      - EDC_UI_ACTIVE_PROFILE=sovity-open-source
      - EDC_UI_CONFIG_URL=edc-ui-config
      - EDC_UI_DATA_MANAGEMENT_API_URL=http://localhost:11002/api/v1/management
      - EDC_UI_DATA_MANAGEMENT_API_KEY=ApiKeyDefaultValue
      - EDC_UI_CATALOG_URLS=http://edc:11003/api/v1/ids/data
  edc:
    image: ghcr.io/sovity/edc-dev:latest
    depends_on:
      - postgresql
    environment:
      MY_EDC_NAME_KEBAB_CASE: 'example-connector'
      MY_EDC_TITLE: 'EDC Connector'
      MY_EDC_DESCRIPTION: 'getting started EDC Connector'
      MY_EDC_CURATOR_URL: 'https://truzzt.eu'
      MY_EDC_CURATOR_NAME: 'truzzt GmbH'
      MY_EDC_MAINTAINER_URL: 'https://truzzt.eu'
      MY_EDC_MAINTAINER_NAME: 'truzzt GmbH'

      # Data Management API Key
      EDC_API_AUTH_KEY: ApiKeyDefaultValue

      MY_EDC_FQDN: 'edc'
      MY_EDC_PROTOCOL: 'http://'
      MY_EDC_IDS_BASE_URL: 'http://edc:11003' # adds missing port

      MY_EDC_JDBC_URL: jdbc:postgresql://postgresql:5432/edc
      MY_EDC_JDBC_USER: edc
      MY_EDC_JDBC_PASSWORD: edc
      EDC_WEB_REST_CORS_ENABLED: 'true'
      EDC_WEB_REST_CORS_HEADERS: 'origin,content-type,accept,authorization,x-api-key'
      EDC_WEB_REST_CORS_ORIGINS: '*'
    ports:
      - '11001:11001'
      - '11002:11002'
      - '11003:11003'
      - '11004:11004'
      - '11005:5005'
  postgresql:
    image: docker.io/bitnami/postgresql:15
    restart: always
    environment:
      POSTGRESQL_USERNAME: edc
      POSTGRESQL_PASSWORD: edc
      POSTGRESQL_DATABASE: edc
